name: MLR_env
channels:
  - nvidia
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - numpy
  - pandas
  - scipy
  - opencv
  - pillow
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1
  - pip
  - pip:
      - ultralytics
