name: MLR_env
channels:
  - defaults
  - conda-forge
  - fastai
  - pytorch  # Add the PyTorch channel to ensure compatibility
dependencies:
  - python=3.11
  - numpy
  - pandas
  - scipy
  - pip
  - opencv
  - kaggle
  - pillow
  - fastai
  - pip:
    - fastai
    - torch==2.6.0+cu126  # Install the specific torch version from the official PyTorch index
    - torchvision
    - torchaudio
    - --extra-index-url https://download.pytorch.org/whl/cu126  # Use the custom PyTorch CUDA index URL
