name: myenv
channels:
  - defaults
  - conda-forge
dependencies:
  - numpy
  - pandas
  - scipy
  - opencv
  - kaggle
  - pillow
  - fastai
  - pip
  - pip:
      - ultralytics
      - fastai
      - torch==2.6.0+cu126
      - torchvision
      - torchaudio
      - "pip install torch==2.6.0+cu126 torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu126"
